import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ReportData, COCEvent } from '../types';
import { formatBytes, formatDate } from '../utils';

export class ReportGenerator {
  static async generatePDF(reportData: ReportData): Promise<Blob> {
    const doc = new jsPDF();
    let yPos = 20;

    doc.setFontSize(20);
    doc.text('CaseVault Pro - Evidence Report', 105, yPos, { align: 'center' });
    yPos += 15;

    doc.setFontSize(12);
    doc.text('Case Information', 20, yPos);
    yPos += 7;

    doc.setFontSize(10);
    doc.text(`Case Number: ${reportData.caseInfo.caseNumber}`, 25, yPos);
    yPos += 5;
    doc.text(`Case Name: ${reportData.caseInfo.caseName}`, 25, yPos);
    yPos += 5;
    doc.text(`Case Officer: ${reportData.caseInfo.caseOfficer}`, 25, yPos);
    yPos += 5;
    if (reportData.caseInfo.department) {
      doc.text(`Department: ${reportData.caseInfo.department}`, 25, yPos);
      yPos += 5;
    }
    doc.text(`Date Opened: ${formatDate(reportData.caseInfo.dateOpened)}`, 25, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.text('Summary', 20, yPos);
    yPos += 7;

    doc.setFontSize(10);
    doc.text(`Total Files: ${reportData.summary.totalFiles}`, 25, yPos);
    yPos += 5;
    doc.text(`Total Size: ${formatBytes(reportData.summary.totalSize)}`, 25, yPos);
    yPos += 5;
    doc.text(`Generated By: ${reportData.summary.generatedBy}`, 25, yPos);
    yPos += 5;
    doc.text(`Generated At: ${formatDate(reportData.summary.analysisCompletedAt)}`, 25, yPos);
    yPos += 10;

    for (const file of reportData.files) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(12);
      doc.text(`File: ${file.fileName}`, 20, yPos);
      yPos += 7;

      const fileInfo = [
        ['Hash (SHA-256)', file.fileHash],
        ['Size', formatBytes(file.fileSize)],
        ['Type', file.fileType],
        ['Analyzed', formatDate(file.analysisDate)],
      ];

      if (file.tags.length > 0) {
        fileInfo.push(['Tags', file.tags.join(', ')]);
      }

      autoTable(doc, {
        startY: yPos,
        head: [['Property', 'Value']],
        body: fileInfo,
        theme: 'grid',
        headStyles: { fillColor: [15, 23, 42] },
        margin: { left: 25 },
      });

      yPos = (doc as any).lastAutoTable.finalY + 5;

      if (file.metadata && Object.keys(file.metadata).length > 0) {
        doc.setFontSize(10);
        doc.text('Metadata:', 25, yPos);
        yPos += 5;

        const metadataRows = this.flattenMetadata(file.metadata);
        autoTable(doc, {
          startY: yPos,
          body: metadataRows,
          theme: 'striped',
          margin: { left: 30 },
        });

        yPos = (doc as any).lastAutoTable.finalY + 5;
      }

      if (reportData.includeCOC && file.chainOfCustody && file.chainOfCustody.length > 0) {
        if (yPos > 200) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(10);
        doc.text('Chain of Custody:', 25, yPos);
        yPos += 5;

        const cocRows = file.chainOfCustody.map((event) => [
          formatDate(event.timestamp),
          event.activityType,
          event.userFullName,
          event.digitalSignature.substring(0, 16) + '...',
        ]);

        autoTable(doc, {
          startY: yPos,
          head: [['Timestamp', 'Activity', 'User', 'Signature']],
          body: cocRows,
          theme: 'grid',
          headStyles: { fillColor: [124, 58, 237] },
          margin: { left: 30 },
        });

        yPos = (doc as any).lastAutoTable.finalY + 10;
      }
    }

    return doc.output('blob');
  }

  static async generateJSON(reportData: ReportData): Promise<Blob> {
    const jsonString = JSON.stringify(reportData, null, 2);
    return new Blob([jsonString], { type: 'application/json' });
  }

  static async generateCSV(reportData: ReportData): Promise<Blob> {
    let csv = '';

    // Add case information header
    csv += 'CaseVault Pro - Evidence Report\n';
    csv += `Case Number,${this.escapeCSV(reportData.caseInfo.caseNumber)}\n`;
    csv += `Case Name,${this.escapeCSV(reportData.caseInfo.caseName)}\n`;
    csv += `Case Officer,${this.escapeCSV(reportData.caseInfo.caseOfficer)}\n`;
    if (reportData.caseInfo.department) {
      csv += `Department,${this.escapeCSV(reportData.caseInfo.department)}\n`;
    }
    csv += `Date Opened,${reportData.caseInfo.dateOpened}\n`;
    csv += `Generated By,${this.escapeCSV(reportData.summary.generatedBy)}\n`;
    csv += `Generated At,${reportData.summary.analysisCompletedAt}\n`;
    csv += '\n';

    // Add summary
    csv += 'Summary\n';
    csv += `Total Files,${reportData.summary.totalFiles}\n`;
    csv += `Total Size (bytes),${reportData.summary.totalSize}\n`;
    csv += '\n';

    // Add file details header
    csv += 'File Name,File Hash (SHA-256),File Size (bytes),File Type,Analysis Date,Tags\n';

    // Add file rows
    for (const file of reportData.files) {
      csv += `${this.escapeCSV(file.fileName)},`;
      csv += `${file.fileHash},`;
      csv += `${file.fileSize},`;
      csv += `${this.escapeCSV(file.fileType)},`;
      csv += `${file.analysisDate},`;
      csv += `${this.escapeCSV(file.tags.join('; '))}\n`;
    }

    // Add Chain of Custody section if included
    if (reportData.includeCOC) {
      csv += '\n';
      csv += 'Chain of Custody Events\n';
      csv += 'File Name,Timestamp,Activity Type,User,User Email,IP Address,Digital Signature,Previous Signature\n';

      for (const file of reportData.files) {
        if (file.chainOfCustody && file.chainOfCustody.length > 0) {
          for (const event of file.chainOfCustody) {
            csv += `${this.escapeCSV(file.fileName)},`;
            csv += `${event.timestamp},`;
            csv += `${event.activityType},`;
            csv += `${this.escapeCSV(event.userFullName)},`;
            csv += `${this.escapeCSV(event.userEmail)},`;
            csv += `${this.escapeCSV(event.ipAddress || 'N/A')},`;
            csv += `${event.digitalSignature},`;
            csv += `${event.previousSignature || 'N/A'}\n`;
          }
        }
      }
    }

    return new Blob([csv], { type: 'text/csv' });
  }

  private static escapeCSV(value: string): string {
    if (value.includes(',') || value.includes('"') || value.includes('\n')) {
      return `"${value.replace(/"/g, '""')}"`;
    }
    return value;
  }

  private static flattenMetadata(metadata: any, prefix = ''): string[][] {
    const result: string[][] = [];

    for (const key in metadata) {
      const value = metadata[key];
      const fullKey = prefix ? `${prefix}.${key}` : key;

      if (value && typeof value === 'object' && !Array.isArray(value)) {
        result.push(...this.flattenMetadata(value, fullKey));
      } else {
        result.push([fullKey, String(value)]);
      }
    }

    return result;
  }

  static downloadFile(content: Blob | string, fileName: string, mimeType: string) {
    const blob =
      content instanceof Blob
        ? content
        : new Blob([content], { type: mimeType });

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
